---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cloud-dancav-io-v1-awsiamrasession
  failurePolicy: Fail
  name: mawsiamrasession-v1.kb.io
  rules:
  - apiGroups:
    - cloud.dancav.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsiamrasessions
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cloud-dancav-io-v1-awsiamrasession
  failurePolicy: Fail
  name: vawsiamrasession-v1.kb.io
  rules:
  - apiGroups:
    - cloud.dancav.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - awsiamrasessions
  sideEffects: None
