apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - name: mpod-v1.kb.io
    objectSelector:
      matchExpressions:
        - { key: app.kubernetes.io/name, operator: NotIn, values: [aws-iamra-manager] }
