#!/usr/bin/env bash
set -eu

ARM="linux/arm64"
X86="linux/amd64"

target_platform="$1"

if [[ "$target_platform" != "$ARM" && "$target_platform" != "$X86" ]]; then
    echo "$target_platform is not a supported platform"
    exit 1
fi

arch=""
if [[ "$target_platform" == "$ARM" ]]; then
    arch="Aarch64"
elif [[ "$target_platform" == "$X86" ]]; then
    arch="X86_64"
fi

wget "https://rolesanywhere.amazonaws.com/releases/1.3.0/${arch}/Linux/aws_signing_helper"
chmod +x ./aws_signing_helper
