---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - cloud.dancav.io
  resources:
  - awsiamrasessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.dancav.io
  resources:
  - awsiamrasessions/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.dancav.io
  resources:
  - awsiamrasessions/status
  verbs:
  - get
  - patch
  - update
